version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/imageapp
      - JWT_SECRET=4800d71386f9859ec53c607e867601c3
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongo_data: